name: ruta_cli
description: A CLI tool to build and run Ruta servers.
version: 0.1.3
repository: https://github.com/k0zlov/ruta_cli
homepage: https://github.com/k0zlov/ruta_cli

executables:
  ruta: ruta_cli

environment:
  sdk: ^3.5.4

dependencies:
  args: ^2.5.0          # For parsing CLI arguments
  process_run: ^0.14.0  # For running shell commands (build_runner, dart run)
  ruta_generator: ^0.1.2

dev_dependencies:
  very_good_analysis: ^5.1.0
